server:
  port: 8080

blogstack:
  roles:
    adminrole: BLOGSTACK-ADMIN
    userrole: BLOGSTACK-USER

  service:
    base-endpoint:
      usermanagementservice:
        authenticationcontroller: /v1.0/authentication/
        rolecontroller: /v1.0/role/
        usercontroller: /v1.0/user/
      qnahubservice:
        questionscontroller: /v1.0/question/
        answerscontroller: /v1.0./answer/
        commentscontroller: /v1.0/comment/
        subcategorycontroller: /v1.0/subcategory/

  usermanagement:
    getbyemail:
      endpoint: http://localhost:9091/v1.0/user/
spring:
  application:
    name: API-GATEWAY
  cloud:
#    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:4200"
#            allowedHeaders: "*"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
      routes:
        - id: BLOGSTACK-QNA-HUB-SERVICE
          uri: http://localhost:9090
          predicates:
            - Path=/v1.0/question/**,/v1.0/answer/**,/v1.0/comment/**,/v1.0/subcategory/**

        - id: USER-MANAGEMENT-SERVICE
          uri: http://localhost:9091
          predicates:
            - Path=/v1.0/authentication/**,/v1.0/user/**



service-version: v1.0
authentication-controller-endpoint: /v1.0/authentication/





