server:
  port: 8080

blogstack:
  usermanagement:
    getbyemail:
      endpoint: http://ec2-18-212-53-8.compute-1.amazonaws.com:9091/v1.0/user/
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
#        - id: USER-SERVICE
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/userservice/**

        - id: USER-MANAGEMENT-SERVICE
          uri: http://ec2-18-212-53-8.compute-1.amazonaws.com:9091
          predicates:
            - Path=/v1.0/authentication/**,/v1.0/user/**




