server:
  port: 8080

blogstack:
  usermanagement:
    getbyemail:
      endpoint: http://ec2-18-212-53-8.compute-1.amazonaws.com:9091/v1.0/user/
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: BLOGSTACK-QNA-HUB-SERVICE
          uri: http://ec2-18-212-53-8.compute-1.amazonaws.com:9091
          predicates:
            - Path=/v1.0/question/**,/v1.0/answer/**,/v1.0/comment/**,/v1.0/subcategory/**

        - id: USER-MANAGEMENT-SERVICE
          uri: http://ec2-18-212-53-8.compute-1.amazonaws.com:9091
          predicates:
            - Path=/v1.0/authentication/**,/v1.0/user/**



service-version: v1.0



