server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  main:
    allow-circular-references: true
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: DEMO-SERVICE
          uri: lb://DEMO-SERVICE
          predicates:
            - Path=/api/demo/**

        - id: MASTER-SERVICE
          uri: lb://ec2-18-212-64-146.compute-1.amazonaws.com:9090
          predicates:
            - Path=/question/**
          filters:
            - name: CircuitBreaker
              args:
                name: MASTER-SERVICE
                fallbackuri: forward:/fallback/blog-stack

        - id: BLOGSTACKIAMSERVICE
          uri: lb://BLOGSTACKIAMSERVICE
          predicates:
            - Path=/authentication/**
          filters:
            - name: CircuitBreaker
              args:
                name: BLOGSTACKIAMSERVICE
                fallbackuri: forward:/fallback/blog-stack
