server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  application:
    name: API-GATEWAY
  cloud:
   gateway:
      routes:
        - id: QNAHUB-SERVICE
          uri: http://localhost:9090
          predicates:
            - Path=/v1.0/question/**,/v1.0/answer/**,/v1.0/comment/**

        - id: USERMANAGEMENTSERVICE
          uri: http://localhost:9095
          predicates:
            - Path=/v1.0/authentication/**,/v1.0/role/**,/v1.0/user/**

        - id: COMMONSERVICE
          uri: http://localhost:9091
          predicates:
            - Path=/v1.0/category/**,/v1.0/file-upload/**,/v1.0/sub-category/**

        - id: BLOGHUBSERVICE
          uri: http://localhost:9092
          predicates:
            - Path=/v1.0/blog/**,/v1.0/blog-comments/**
